entity: CredentialIssuer
record:
  id: 'Gateway Services Resource Server'
  namespace: platform
  description: 'Authorization Profile for protecting the Gateway Services API'
  flow: client-credentials
  mode: auto
  clientAuthenticator: client-secret
  authPlugin: jwt-keycloak
  clientRoles: []
  availableScopes: []
  resourceType: platform
  resourceAccessScope: Namespace.Manage
  resourceScopes:
    - Namespace.Manage
    - Namespace.View
    - Access.Manage
    - GatewayConfig.Publish
    - Content.Publish
  owner: user_api-owner
  environmentDetails:
    - environment: prod
      issuerUrl: '{OIDC_ISSUER}'
      clientId: '{OIDC_CLIENT_ID}'
      clientSecret: '{OIDC_CLIENT_SECRET}'
      clientRegistration: managed
