version: '3.2'

services:
  cypress:
    image: 'aps-cypress-e2e:latest'
    container_name: cypress-e2e
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./results/report:/e2e/results/report
