components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas: {}
    securitySchemes: {}
info:
    title: bcgov-aps-portal
    version: 0.1.0
    description: 'The APS API Services Portal'
    license:
        name: MIT
    contact:
        name: 'BC Gov APS'
openapi: 3.0.0
paths:
    '/namespaces/{ns}/contents':
        put:
            operationId: PutContent
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security:
                -
                    jwt:
                        - Content.Publish
            parameters:
                -
                    in: path
                    name: ns
                    required: true
                    schema:
                        type: string
    '/namespaces/{ns}/contents/{contentId}/markdown':
        put:
            operationId: PutMarkdown
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security:
                -
                    jwt:
                        - Content.Publish
            parameters:
                -
                    in: path
                    name: contentId
                    required: true
                    schema:
                        type: string
    '/namespaces/{ns}/datasets':
        put:
            operationId: Put
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security:
                -
                    jwt:
                        - Namespace.Manage
            parameters:
                -
                    in: path
                    name: ns
                    required: true
                    schema:
                        type: string
    /directory:
        get:
            operationId: List
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security: []
            parameters: []
    '/directory/{id}':
        get:
            operationId: Get
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security: []
            parameters:
                -
                    in: path
                    name: id
                    required: true
                    schema:
                        type: string
    /documentation:
        get:
            operationId: List
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security: []
            parameters: []
    '/documentation/{slug}':
        get:
            operationId: Get
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security: []
            parameters:
                -
                    in: path
                    name: slug
                    required: true
                    schema:
                        type: string
    '/identifiers/{type}':
        get:
            operationId: GetNewID
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                type: string
            security: []
            parameters:
                -
                    in: path
                    name: type
                    required: true
                    schema:
                        type: string
    '/namespaces/{ns}/products':
        put:
            operationId: Put
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
            security:
                -
                    jwt:
                        - Namespace.Manage
            parameters:
                -
                    in: path
                    name: ns
                    required: true
                    schema:
                        type: string
servers:
    -
        url: /ds/api
