kind: Product
appId: 2B04C28E08AT
name: New-Auto Test Product
dataset: new-auto-test-product
namespace: permission
environments:
  - id: 1F7CA929
    name: dev
    active: true
    approval: true
    legal: terms-of-use-for-api-gateway-1
    flow: kong-api-key-acl
    additionalDetailsToRequest: Please provide a bit more of this
    services: []
