name: Build and Deploy Cypress and Execute Tests

on:
  push:
    branches:
      - 'util/automation-*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:4.11.0
    steps:
      - uses: actions/checkout@v1
      - run: |
          cd e2e
          npm install --production
          npm run cy:run --config-file cypress.json
