name: Build and Deploy Cypress and Execute Tests

on:
  push:
    branches:
      - 'util/automation-*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    steps:
      - uses: actions/checkout@v1
      - name: Spin up API Services Portal and Run E2E Tests
        run: docker-compose -f docker-compose.yml up -d
      - name: Stop the Containers
        run: |
          while true; do
            if [ "$(docker ps -aq -f status=exited -f name=cypress-e2e)" ]; then
              # cleanup
              docker-compose stop
              sleep 1m
              docker-compose down
              break
            else
              docker ps -a
              echo  "Waiting for Cypress to Complete E2E Tests....."
              sleep 1m
            fi
          done
