name: Build and Deploy Cypress and Execute Tests

on:
  push:
    branches:
      - 'util/automation-*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
      options: -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/home/nkuruba/nithin/Git/api-services-portal
    steps:
      - uses: actions/checkout@v1
      - name: Spin up API Services Portal and Run E2E Tests
        run: docker-compose -f docker-compose.yml up
      - name: Stop the Containers
        run: |
          while true; do
            if [ "$(docker ps -aq -f status=exited -f name=keycloak)" ]; then
              # cleanup
              docker-compose stop
              sleep 1m
              docker-compose down
              break
            else
              docker ps -a
              echo  "Waiting for Cypress to Complete E2E Tests....."
              sleep 1m
            fi
          done
