name: Scan for Vulnerabilities in API Services Portal Container Image

on:
  push:
    branches: [dev, main, scan/*]

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bcgov/api-services-portal:scan
      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@main
        with:
          image: 'bcgov/api-services-portal:scan'
          acs-report-enable: true
          fail-build: false
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bcgov/api-services-portal:scan'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
