name: Delete Feature

on:
  delete:
    branches: [ feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ${{ env.REGISTRY }}/bcgov/aps-portal/aps-portal

    - name: Set DEPLOY_ID which will delete a custom deploy from 'dev' environment
      run: echo '::set-output name=DEPLOY_ID::${{ steps.docker_meta.outputs.tags }}'
      id: set-deploy-id

    - name: Get deploy ID
      run: echo "The DEPLOY_ID is ${{ steps.set-deploy-id.outputs.DEPLOY_ID }}"

    - uses: actions/checkout@v2
      
    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        version: '4.6'

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

        # Disables SSL cert checking. Use this if you don't have the certificate authority data.
        insecure_skip_tls_verify: true

        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        
    - name: 'Delete Network Security Policy'
      run: |
        echo """
        kind: NetworkSecurityPolicy
        apiVersion: security.devops.gov.bc.ca/v1alpha1
        metadata:
          name: proto-aps-portal-${{ steps.set-deploy-id.outputs.DEPLOY_ID }}
        """ > nsp.yaml
        oc delete -f nsp.yaml

    - name: 'Get Helm'
      run: |
        curl -L -O https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
        tar -xf helm-v3.4.2-linux-amd64.tar.gz

    - name: 'Delete ALL'
      run: |
        export PATH=$PATH:`pwd`/linux-amd64
       
        helm delete proto-aps-portal-${{ steps.set-deploy-id.outputs.DEPLOY_ID }}-db
        helm delete proto-aps-portal-${{ steps.set-deploy-id.outputs.DEPLOY_ID }}
        helm delete proto-aps-portal-${{ steps.set-deploy-id.outputs.DEPLOY_ID }}-routes
